# -*- coding: utf-8 -*-
"""TT002 Aula 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B50bgkTVS9xtvd3Sk0OLFc0wl-JWKc6u
"""

# string1 = input()
# string2 = input()
string1 = "aaa"
string2 = "bbb"
concat = ""
if not len(string1) == len(string2):
    print("As strings precisam ter o mesmo tamanho para prosseguir!")
else:
    for i in range(len(string1)):
        concat += string1[i] + string2[i]
    print(concat)

# string1 = input()
# string2 = input()
string1 = "aaaaaa"
string2 = "bbb"
stringlen = [len(string1), len(string2)]
concat = ""
for i in range(min(stringlen)):
    concat += string1[i] + string2[i]
concat += string1[min(stringlen):] + string2[min(stringlen):]
print(concat)

def mesclar_list(list1: list, list2: list):
    palavra_mesclada = []
    for i in range(5):
        string1 = list1[i]
        string2 = list2[i]

        stringlen = [len(string1), len(string2)]
        concat = ""
        for i in range(min(stringlen)):
            concat += string1[i] + string2[i]
        concat += string1[min(stringlen):] + string2[min(stringlen):]
        palavra_mesclada.append(concat)

    return palavra_mesclada

list1 = ["aaa", "aaa", "aaa", "aaa", "aaa"]
list2 = ["bbb", "b", "bbbb", "bbb", "bbbbbb"]

# list1 = []
# list2 = []
# for i in range(5):
#     list1.append(input())
# for i in range(5):
#     list2.append(input())

palavra_mesclada = mesclar_list(list1, list2)
print(palavra_mesclada)